<?php
/**
 * This namespace provides PHP helpers for loading assets built using wp-scripts.
 * Script-only: Use normal wp_(enqueue|register)_style methods for handling CSS.
 * Refer to the wp-scripts documentation for background context:
 *
 * @see https://developer.wordpress.org/block-editor/getting-started/devenv/get-started-with-wp-scripts/
 */
declare( strict_types=1 );

namespace WikimediaDiff\Asset_Loader;

/**
 * Register a script asset. Loads dependencies and version information from the
 * PHP asset file.
 *
 * @param string   $handle          Handle to use for the script.
 * @param string   $asset_file_path Path to this script's asset.php file.
 * @param string   $script_uri      Public URI of the script file.
 * @param string[] $additional_deps Optional list of additional script handles on which
 *                                  this asset depends. Gets merged with the asset.php
 *                                  autogenerated WP dependencies list.
 */
function register_script_asset( string $handle, string $asset_file_path, string $script_uri, array $additional_deps = [] ) : void {
	// phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable
	$asset_file = include( $asset_file_path );

	$asset_file['dependencies'] = array_merge( $asset_file['dependencies'] ?? [], $additional_deps );

	// Check whether a runtime chunk exists, and inject it as a dependency if it does.
	if ( Utilities\includes_hmr_dependency( $asset_file['dependencies'] ) ) {
		// Warn if we aren't using SCRIPT_DEBUG when we need to.
		Utilities\warn_if_script_debug_not_enabled( $asset_file );
		// Try to infer and depend upon our custom runtime chunk (see webpack.config.js).
		$runtime_handle = Utilities\detect_and_register_runtime_chunk( $asset_file_path, $script_uri );
		if ( ! empty( $runtime_handle ) ) {
			$asset_file['dependencies'][] = $runtime_handle;
		}
	}

	wp_register_script(
		$handle,
		$script_uri,
		$asset_file['dependencies'],
		$asset_file['version'] ?? filemtime( $asset_file_path ),
		// Load all first-party scripts in the footer.
		true
	);
}

/**
 * Enqueue a script asset, registering it first if needed. Loads dependencies
 * and version information from the PHP asset file.
 *
 * @param string   $handle          Handle to use for the script.
 * @param string   $asset_file_path Path to this script's asset.php file.
 * @param string   $script_uri      Public URI of the script file.
 * @param string[] $additional_deps Optional list of additional script handles on which
 *                                  this asset depends. Gets merged with the asset.php
 *                                  autogenerated WP dependencies list.
 */
function enqueue_script_asset( string $handle, string $asset_file_path, string $script_uri, array $additional_deps = [] ) : void {
	if ( ! wp_script_is( $handle, 'registered' ) ) {
		register_script_asset( $handle, $asset_file_path, $script_uri, $additional_deps );
	}
	wp_enqueue_script( $handle );
}
